package.json

Правит уязвимость pug из вкладки "Security". 
В самом обновлении кроме этого фикса есть только прекращение поддержки восьмой ноды

Обновить e11y до 0.12

---

package-lock.json

Потому, что @nlopin [прав](https://github.com/Y-Doka/platform/pull/50#issuecomment-819061339)
> С текущей конфигурацией у нас появляется дополнительный шаг для сетапа, если использовать рекомендуемую версию ноды:
> 
>     * установи lts ноду
> 
>     * обнови npm до семёрки
> 
> 
> В четырнадцатую ноду включен предыдущий npm@6, который не умеет вторую версию локфайла. Семерка есть либо в экспериментальной 15-й либо в выходящей через неделю 16-й. Проблема с том, что шеснатдцатая перейдет в статус LTS только в октябре.
> 
> Предлагаю опять откатить локфайл до первой версии 😄

Возвращает лок-файл v1

---

src/includes/collections/tools-articles.njk

- Вместо инструментов выводились статьи из раздела CSS

Правит ошибку в подборке в боковой панели

---

.eleventy.js
netlify.toml
src/pages/404.njk

- Добавляет 404 страницу на виртуальном сервере ([инструкция](https://www.11ty.dev/docs/quicktips/not-found/#with-serve))
- Переносит `netlify.toml`, который будет делать 404 страницу на стороне провайдера.

Добавляет 404 страницу

---

.eleventy.js
package-lock.json
package.json

Fix: #160
Предлагается другой подход к преобразованиям в html. Вместо работы с регулярными выражениями лучше построить в памяти DOM (в данном случае с помощью библиотеки LinkeDOM, аналог JSDOM).
Этот же подход можно использовать для создания _picture_ внутри контента. А также чтобы добавить CSS-классы ко всем элементам внутри контента.

Правит пути в практиках для ресурсов

---

src/views/doc.11tydata.js
src/views/doc.njk

Fallback-дата была убрана, но [иногда возникают случаи](https://github.com/doka-guide/content/issues/1177), что файл `index.11tydata.json` не создается. Поэтому вообще не выводим блок с датой, чтобы не было падения сборки.

Предотвращает падение сборки, если нет поля `updatedAt`

---

src/includes/analytics/metrika.njk
src/layouts/base.njk

Подключает дефолтную метрику от Яндекса + добавляет альтернативный CDN «Позволяет корректно учитывать посещения из регионов, в которых ограничен доступ к ресурсам Яндекса»

Добавляет метрику

---

src/includes/practices.njk

В блоке «В работе» у мнений авторов не было ссылок-якорей. Этот PR:
- Добавляет якоря для каждого мнения
- Добавляет быстрые ссылки для каждого мнения
- Якоря уникальны
- Якоря содержат уникальный для статьи `aria-label`
Было
Стало

Добавляет якоря для мнений авторов

---

gulpfile.js
package-lock.json
package.json

Для файлов стилей и скриптов добавляет хеш типа `index.css -> index-hash1234.css` для сброса кэша в бразуерах.
Для этого используется два пакета для gulp - один создаёт файл-манифест с хешами для нужных файлов, другой заменяет url на эти файлы, используя этот манифест.
В будущем, это решение может быть спорным, так как из-за малого размера файлов и для повышения рейтинга в поисковых выдачах эти файлы можно инлайнить в тело html-страничек.

Добавляет хеширование для файлов CSS и JS для инвалидации кэша

---

package-lock.json
package.json

Если у пользователя не установлена подсистема Linux для Windows (а значит и Linux-версия Bash), пользователь сталкивается с проблемой:
```bash
"NODE_ENV" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `NODE_ENV=development eleventy --serve --quiet`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Лучше не заставлять пользователя ставить подсистему Linux, которая ему может быть не нужна, а воспользоваться [пакетом cross-env](https://www.npmjs.com/package/cross-env), который предназначен для решения проблемы.

Добавляет cross-env

---

.eleventy.js

В связи с [обсуждением](https://github.com/doka-guide/content/discussions/1343) стало очевидным, что нужно копировать файлы демок все, а не только `html` и картинки с архивами.

Добавляет фильтр для копирования файлов демок

---

src/styles/blocks/index-section.css

На странице индексов может можеть быть баг, свзяанный с column-layout, при котором колонки разрываются в местах margin, поэтому они заменены на padding. Дополнительно сделан рефакторинг для использования custom properties

Предотвращает перенос колонок

---

.eleventy.js
src/styles/blocks/code-block.css
src/styles/code-dark-theme.css
src/styles/code-light-theme.css
src/styles/dark-theme.css
src/styles/index.css
src/transforms/code-transform.js

- пока нет дизайна для оформления кода добавлены темы _one light_ и _one dark_
- вместо замещения оригинального блока с кодом делается его копия и добавляется отдельный блок с номерами строк - это позволить проще реализовывать копирование сниппета кода
- нумерация сделана в виде таблицы

Рефактор блоков с кодом

---

src/styles/blocks/footer.css

Safari некорректно показывает [flex-контейнер с `column-reverse` и `gap`](https://bugs.webkit.org/show_bug.cgi?id=225278)

Фикс бага в Safari для `column-reverse` и `gap`

---

src/data/pageType.js
src/includes/meta.njk
src/layouts/base.njk
src/views/doc.11tydata.js

По умолчанию добавляет всем страницам `itemtype="https://schema.org/WebPage"`. Статьям - `itemtype="https://schema.org/Article"`
PR cвязан с этой [задачей](https://github.com/doka-guide/platform/issues/341)

Добавляет типы страниц для Schema

---

src/scripts/modules/search.js
src/styles/blocks/articles-group.css
src/styles/blocks/search-hit.css

- устраняет  слипание слов в названиях статей в индексах
- рендерит теги `code` в результатах поиска

Фикс багов с рендером тегов `<code>`

---

package-lock.json
src/transforms/code-transform.js

Если в заголовке статьи больше одного слова с бэктиками, классы для стилей добавляются только к первому. 
Пример [статья js/try...catch](https://github.com/doka-guide/content/blob/main/js/try-catch/index.md)
```njk
---
title: "`try`...`catch`"
```
БЫЛО
```html
<h1 class="article__title">
<code class="article__title-code font-theme font-theme--code">try</code>...<code>catch</code>
</h1>
```
```html
<li>
<a class="articles-group__link link" href="/js/try-catch/">
<code class="articles-group__code font-theme font-theme--code">try</code>...<code>catch</code>
</a>
</li>
```
СТАЛО
```html
<h1 class="article__title">
<code class="article__title-code font-theme font-theme--code">try</code>...<code class="article__title-code font-theme font-theme--code">catch</code>
</h1>
```
```html
<li>
<a …
```

Добавляет обработку множественных бэктиков

---

.eleventy.js

Явно сортирует статьи в лексикографическом порядке, так как [сортировка по умолчанию](https://www.11ty.dev/docs/collections/#sorting) может не подойти

Задает сортировку элементов внутри коллекций категорий в лексикографическом порядке

---

src/views/article-index.11tydata.js

Есть вероятность, что в какой-то момент в группе "Остальные" не будет статей, поэтому добавляется проверка на количество элементов.

Предотвращает вывод пустых групп в индексе

---

src/styles/blocks/article.css
src/styles/blocks/content.css
src/styles/blocks/doc.css

- Предотвращает переполнение из-за тегов `video`, `audio`
- Возвращает случайно удаленные вертикальные отступы для контента статьи
- Увеличивает брейкпойнт для центрирования на широких мониторах

Небольшие правки вёрстки

---

src/views/index.11tydata.js

В контенте [отметили зафичеренные статьи](https://github.com/doka-guide/content/pull/1598). Этот PR выводит на главной зафичеренные статьи.

Раскоменчивает вывод зафичеренных статей

---

src/styles/blocks/article-heading.css

Fix: #410
У Safari некорректно  работает `scroll-margin` для неблочных элементов. При этом хочется сохранить структурное  разделение заголовка и ссылки на него.

Правит скролл для заголовков статьи

---

src/styles/blocks/callout.css
src/styles/blocks/code.css

- Правки размеров
- Правка фонового цвета внутри callout
- принудительный перенос текста
Fix: #392, #395, #390

Правки для блока `<code>`

---

gulpfile.js

У CSSO по умолчанию включена опция `restructure: true`, которая может склеивать селекторы. К багам это не приводило, но может, плюс это затрудняет отладку в production-режиме.

Меняет настройки CSSO

---

src/views/doc.11tydata.js

Уточняет вычисление docPath. Например, для статьи `/css/z-index/index` ранее преобразовывался в `/css/z-/index`.

Правит вычисление `docPath`

---

src/views/doc.11tydata.js

Fix: #440
Раньше проверялось просто вхождение подстроки, из-за чего пути `/js/string` и `js/string-length` считались одинаковыми.

Правит метод поиска практик для статьи

---

src/styles/blocks/featured-article.css

Чинит  #450
Было (смотреть левый квадрат):
Стало (смотреть левый квадрат):

Убирает подчёркивание при наведении в Safari 15

---

src/transforms/code-transform.js

Текущий способ подгрузки языков в prismjs приводит к подвисанию watch-процесса при многократных изменениях исходников в dev-режиме

Загружает все языки для PrismJS заранее

---

src/includes/blocks/featured-article.njk

Убирает лишнюю подсказку, которая мешала чтению.

Убирает `title` со ссылок на зафичеренных статьях на главной

---

src/includes/blocks/article-image.njk
src/includes/contributors.njk
src/includes/meta.njk
src/views/doc.njk

Fix: #672
- Удаляет лишниюю запятую в ld+json
- Добавляет url для авторов в ld+json
- Добавляет изображения в ld+json
- Приводит даты к ISO-формату в ld+json
- Задаёт корректный `headline` в ld+json (был не заголовок, а url)
- Расставляет sсhema-атрибуты в статье

Правит ошибки и предупреждения Google для метаданных статьи

---

src/styles/blocks/block-code.css
src/styles/blocks/callout.css
src/styles/blocks/inline-code.css
src/styles/index.css
src/styles/index.sc.css
src/transforms/code-transform.js

Fix: #723
Prism делает подсветку блоков кода внутри markdown, то есть, если в статье будет такой блок кода:
`````
````md
Пример кода на js:
```javascript
function add(x, y) {
return x + y;
}
```
````
`````
то он выполнит токенизацию для js-блока.
Проблема просто в пересечении стилей - на вложенных блоках prism добавляет классы `code`, `code-snippet`, `code-block`. Поэтому сделал переименование CSS-классов.

Правка пересечения стилей prism при рендере блоков кода внутри markdown-блоков с кодом

---

.eleventy.js
package-lock.json
package.json

Старая версия работала путём расширения синтаксиса makdown через пакет markdown-it-container.

Удаляет обработку старой версии callout.

---

src/views/index.njk

Пример: при переходе с главной страницы на группу индекса `https://doka.guide/html#osnovy` Safari добавляет `/` перед `#` - `https://doka.guide/html/#osnovy`. Затем, какую бы группу на главной ни выбрали, например, `https://doka.guide/html#semantika`, Safari будет перенаправлять на снова `https://doka.guide/html/#osnovy`.
Решение: явно добавить слеши `/`.

Правит баг с некорректным выставлением hash в safari на странице индексов

---

src/scripts/modules/articles-index.js

- Убирает проверку на Chrome
- Делает выравнивание скролла по верхнему краю
Fix: #818

Правит скролл для anchor-блока на индексной странице

---

src/includes/blocks/search-category.njk
src/includes/blocks/search-tags.njk
src/includes/blocks/search.njk
src/scripts/modules/search.js
src/styles/blocks/tag-filter.css
src/views/search.njk

Изменения:
- нормализует тег title, чтобы не было "Дока - Поиск - Дока"
- меняет CSS для контролов, чтобы рисовались стандартные браузерные стили для фокуса
- меняет имена и значения контролов на более понятные и отвязанные от Algolia, например, вместо `q` теперь `query`, вместо `<input name="filter-category" value="category:html"/>` теперь `<input name="category" value="html"/>`
- меняет radio на checkbox у фильтров категорий (Fix: #421, Fix: #826)
- удаляет атрибут `autocomplete="off"` у радио-инпутов, так как начальные значения теперь выставляются из строки url. Изменённые значения фильтров также сохраняются обратно в url (fix: #784)
- рефакорит код для использования компонентов для фильтров и для рендера результатов

Рефакторит страницу поиска для преобразования состояния фильтров в search params

---

package.json

При синхронизации rsync удаляет ключ на сервере, поэтому в течение некоторого времени отправка формы невозможна.

Добавляет исключениe для rsync

---

src/styles/code-dark-theme.css
src/styles/code-light-theme.css

Ближайший похожий цвет в палитре с достаточной контрастностью это `--mono-2`
Fixes #813

Фикс цвета комментариев в темной теме

---

src/transforms/code-breakify-transform.js

Удалил пока символ `;`, так как ломается вывод `&lt;` и `&gt;`. 
Нужно будет пересмотреть обработку символов.
Можно также решить заменой `&lt;` на `<`, затем добавить `<wbr>` для `<` и заменить обратно на `&lt;`

Добавляет фикс для breakify угловых скобок

---

src/scripts/modules/code-line-numbers.js

Забыли поправить после правок конфликтов именования с бибилотекой prism.js

Правит селекторы в js-модуле расстановки номеров строк

---

src/transforms/image-transform.js

Например, в статье `tools/markdown` в последнем совете есть неэкранированное от преобразований изображение

Добавляет игнорирование преобразований для внешних изображений

---

src/scripts/modules/search.js

В результаты поиска сейчас попадает код из элементов `pre`, там могут встречаться символы обратных кавычек, например, в JavaScript.
Как быстрое решение - удалить обработку бектиков. Другие варианты - в поисковом индексе добавлять тип блока - текст или код - и исходя из него выбирать, обрабатывать или нет кавычки.

Удаляет обработку бектиков в теле поискового сниппета

---

src/scripts/modules/toc.js

Fix: #859
У Chrome вроде больше нет проблем с начальным скроллом до заголовка, по крайней мере на странице статьи. Поэтому js-скролл на событии load можно убрать.

Убирает принудительную якорную js-прокрутку до заголовка

---

make-links.js

Существует проблема медленной работы с контентом на локальной копии сайта, поскольку пока 11ty не поддерживает инкрементальную сборку. Каждое изменение в статье приводит к повторной сборки всего сайта, а это процесс очень не быстрый, учитывая количество материалов.
В этом пиаре модифицируется скрипт для формирования ссылок на контент. Теперь можно выбрать вариант сборки для одной статьи и для всех статей Доки. Достигается результат формированием только необходимых ссылок.

Реализует возможность просмотра только одной статьи

---

src/styles/blocks/article-heading.css
src/styles/blocks/font-theme.css

Правим размеры заголовков четвёртого и пятого уровня в статьях. 
Closes #6
Предыдущая версия заголовков использует шкалу размеров шрифта (xxl, xl, l, m, s, xs). Новые размеры заголовков в этой шкале отсутствуют. 
Я решил не добавлять их в шкалу так как у нас всего один случай использования таких размеров, а создать отдельные переменные для заголовков, которые будут обращаться либо к шкале (заголовки 1,2,3), либо иметь захардкоженые значения (заголовки 4,5).
🎤 Рассказываю про решение на видео:
<a href="https://www.loom.com/share/27e26fc89e6644dfa79b9c9d5d04053e">
<p>Заголовки четвертого и пятого уровней - Watch Video</p>
</a>

Изменяет размеры заголовков четвёртого и пятого уровня

---

src/styles/blocks/search-page.css
src/styles/blocks/search.css

Убрал жёсткое указание ширины, которые вызывало скролл. На экранах от 1024 до 1240 найденный контент будет занимать всю оставшуюся ширину, а после 1240px найденный контент будет увеличиваться с 560 до 809 пикселей.

Убирает скролл на странице поиска (doka-guide/platform#939)

---

src/views/people.njk

Если зайти на страницу участников и кликнуть по заголовке в шапке, мы получим ошибку.
Safari:
Chrome и Яндекс Браузер выдают пустую страницу с URL: `about:blank#blocked`
Firefox на ошибку не реагирует.
Так происходит потому, что на странице людей сломана логика остальных страниц. У страницы нет заголовка (кстати, а нормально, что `<h1>` отсутствует?), а то что имеет название страницы спрятано в «хлебных крошках» и не имеет параметра `pageCategoryId`, который есть на странице каждого конкретного человека. 
Этот PR добавляет такой id, из-за чего ссылка на заголовке на слове «Участники» начинает работать. 
В следующей итерации можно было бы:
1. Вынести заголовок на страницу
1. Убрать ссылку на этом заголовке, она там не нужна.

Фиксит ссылку в шапке на странице участников

---

src/styles/blocks/featured-article.css

Этот пулл реквест обрезает текст троеточием, если заголовок слишком длинный и не влезает в карточку. #965

Чинит заголовок карточки рекомендаций

---

src/styles/blocks/switch.css

Привет! 
На странице поиска обратил внимание на переключатель фильтра поиска в нижнем левом углу экрана. При фокусе внутри там активируется псевдокласс `:focus-within` с голубым `outline`. 
При этом в целом на странице такого больше нет, только на этом переключателе. У других кнопочек стандартная чёрная обводка.
Предложение такое: можно убрать этот голубой `outline`, потому что и код будет проще, и не бьётся он с другими элементами, и его практическая польза неясна.
Было: 
Станет:

Упрощает стиль переключателя фильтра поиска

---

src/includes/blocks/header.njk
src/includes/blocks/logo.njk
src/scripts/modules/header.js
src/scripts/modules/logo.js
src/scripts/modules/quick-search.js
src/scripts/modules/search.js
src/styles/blocks/header.css
src/styles/blocks/logo.css
src/styles/blocks/menu-toggle.css
src/styles/blocks/nav-list.css
src/styles/blocks/search-page.css
src/styles/blocks/search.css
src/views/404.njk
src/views/index.njk
src/views/people.njk
src/views/person.njk
src/views/views.11tydata.js

В соответствии с новым дизайном необходимо изменить логотип, хлебные крошки, размеры всего и работу меню для главной страницы:
Предлагаю обсудить градиенты, которые мы в итоге убрали... Стоит ли к ним возвращаться?
Ещё есть моменты с развёрнутым поиском на мобильном...
Было задумано так:
Сделал так на обсуждение:

Изменяет дизайн хедера

---

src/transforms/code-breakify-transform.js

Привет снова!
Заметил, что некоторые названия методов, по типу `.addEventListener()`, разбиваются в тексте только по спецсимволам, из-за чего возникают такие вот пустоты: 
На мой взгляд, выглядит странно: точка остаётся на одной строке, а остальной текст улетает на следующую, плюс разрезается фон и получается, словно что-то «оторвали». И чем длиннее название метода, например `.getElementsByClassName()`, тем больше эта пустота.
Что, если добавить в функцию небольшую возможность разбивать подобные названия? Поскольку методы из нескольких слов, каждое из которых начинается с заглавной буквы, предложил бы такую логику:
- Если в слове есть заглавные буквы, то:
1. Если НЕ начинается на заглавную, то вставить `<wbr>` перед каждой заглавной;
`.addEventListener() => …

Изменяет переносы слов-названий методов в тексте

---

src/transforms/code-breakify-transform.js

Fix #992
Сделал так, чтобы переносы не ставились для первых спецсимволов в коде. 
Было:
Стало:
Также добавил тройку комментов по коду, чтобы другим было легче разобраться 🙂

Правит переносы имён методов

---

src/markdown-it.js
src/transforms/article-code-blocks-transform.js

Есть предложение привести названия, вроде `JS` или `JavaScript`, к единому шаблону.
Сейчас то так:
То так:
В `src/transforms/article-code-blocks-transform.js` из-за этой путаницы даже есть код, который подглядывает в объект `LANG_ALIASES` в поисках понятной призму записи.
Можно перенести эти исключения из `article-code-blocks-transform` в `src/markdown-it.js` и шаблонизировать названия до того, как вставлять их в атрибут `data-lang`. 
Плюсы: 
1. Можно убрать лишнюю проверку из `article-code-blocks-transform`, поскольку туда всё будет попадать уже шаблонизированным;
2. Везде будет одинаковая запись названий;
3. Авторам не придётся менять `JavaScript` на `JS` или что-то такое. Как хотят, так и пишут, код всё приведёт к единому стилю.
Было:
Стало:
На мой взгляд, так больше порядка 😀

Приводит названия к единому шаблону

---

.eleventy.js
src/styles/blocks/color-picker.css
src/styles/code-dark-theme.css
src/styles/code-light-theme.css
src/styles/index.css
src/transforms/color-picker-transform.js

Появилась идея, как можно было бы решить #895 без обилия кода.
Prism уже разметил цвета в блоках с кодом, и я подумал, что можно воспользоваться этим и добавить фичу с превью цвета.
Получается так:
Тёмная тема:
Из ошибок нашёл две. Первая здесь:
Цвет не отображается, но это можно решить обновлением зависимости, в [последней версии](https://www.npmjs.com/package/prismjs) `RebeccaPurple` [добавлен](https://github.com/PrismJS/prism/pull/3448).
Вторая:
Связано с тем, что у призма пока нет поддержки рэгэкспами нового синтаксиса из примеров, только старого, но, мне кажется, это дело времени, плюс я закинул в их репозиторий предложение такую поддержку добавить дабы посильно ускорить процесс. Можно и обработать эти «непрокрасы» отдельно в коде.
В остальном вроде выглядит интересно 🤔🙂

Добавляет превью цвета в блоках кода

---

src/includes/meta.njk

[По документации](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started)
> twitter:card
> The card type, which will be one of “summary”, “summary_large_image”, “app”, or “player”.
Сейчас Твиттер находит тип карточки `summary_large_image`, потом находит просто `summary`, забывает первый тип и использует последний. Опытным путём кажется, что `summary_large_image` всё же лучше.

Оставляет только один тип карточки для Твиттера

---

src/styles/blocks/color-picker.css
src/transforms/color-picker-transform.js

Отловил пару ошибок в превью цвета внутри блоков кода.
Первая ошибка:
Код выставляет для цвета превью «transparent» собственно `transparent`, и он становится либо белым, либо чёрным в зависимости от темы. Добавил исключение, чтобы `transparent` оставался без превью:
Стало:
Вторая ошибка:
Я добавил отступ для превью, если перед этим есть скобка (чтобы не было слипания). Но вот в таких случаях скобка есть, но отступ не нужен:
Видно, что `red` сдвинулся. Поэтому добавил отступ для скобки, а не для превью.
Стало в уровень:
Предлагаю поправить, чтобы было не только красиво, но и везде всё хорошо 🙃

Правит ошибки превью цвета в блоках кода

---

src/views/index.njk

Предлагаю внести мини-правку по следующей логике.
Участники — это люди, следовательно напротив ссылки должно быть что-то, что олицетворяет либо людей, либо помощь, либо взаимодействие людей и всё в таком духе. А сейчас там огонь, меня это немного смущало всегда 😀
Может поставить вот такой эмоджи: 🙌. Очеловеченный и символизирующий связь. Например.

Меняет эмоджи напротив «Участники»

---

src/scripts/modules/logo.js

Кажется, я не заметил, что в расширенном поиске совсем другие классы поисковых результатов и количество лого 😥, из-за чего анимация выключается только для главной. 
Внёс поддержку страницы расширенного поиска ✏

Добавляет поддержку анимации лого в расширенном поиске

---

src/includes/questions.njk

Раньше в сопроводительном тексте стояла ссылка на общий туториал для контрибьюторов. Теперь ссылка ведёт на инструкцию конкретно для этого раздела.

[На собеседовании] Меняет ссылку на инструкцию

---

src/styles/blocks/callout.css

Fix #1029
Кажется, flex выровнял элементы в строку. Исправил на `column`, вроде ничего?)

Чинит врезки в текст

---

src/includes/questions.njk

В запале долгожданного релиза чуть неправильно был создан шаблон для вопросов для рубрики «На собеседовании». Вытащила иконку из контента, поставила отдельно. Теперь она красиво стоит сбоку от текста, а не над ним.
Было 
Стало

Чинит шаблон врезки вопроса для интервью

---

src/styles/blocks/featured-article.css

Правит размер шрифта для <code> в карточках статей на главной #1037

---

.github/workflows/pr-preview.yml
src/styles/blocks/featured-article.css
src/transforms/headings-anchor-transform.js

Правит размер шрифта для <code> в параграфах с кратким содержанием статьи #1037

---

src/includes/blocks/footer.njk
src/libs/github-contribution-service/github-contribution-service.js
src/styles/blocks/footer.css

ПР в рамках #1054.
Заменила `<div>` и `<span>` на `<fieldset>` и `<legend>` соответственно. Благодаря этому с точки зрения скринридеров это теперь группа чекбоксов с общим названием «Тема». И использовала этот хак с визуально скрытым именем и `<span>`, который скрыт от скринридеров. Он уже используется для других похожих элементов.
Как грустно, что этот баг с позиционированием `<legend>` не пофиксили всё ещё.

Улучшает разметку переключателя тем

---

src/includes/blocks/search.njk
src/libs/github-contribution-service/github-contribution-service.js

У поля поиска сейчас источник имени — `placeholder`. С точки зрения WCAG это допустимо, но на деле это не очень хорошая практика. Для поля поиска допустимо добавлять визуально скрытое имя с помощью HTML или ARIA. Так что я просто добавила скрытый `<label>`.
ПР решает проблему из #1058.

Добавляет скрытый лейбл для поля поиска

---

src/libs/github-contribution-service/github-contribution-service.js
src/scripts/modules/articles-gallery.js

Сейчас в блоках с фичеринг-статьями на главной и 404 страницах клавиатурный фокус после нажатия на кнопку «Показать ещё» оказывается на первой ссылке после пропавшей кнопки — «HTML». Получается, что пользователям клавиатуры для того, чтобы посмотреть какие появились ещё статьи, надо протабывать вверх.
Я слегка изменила скрипт так, чтобы фокус после клика на кнопке устанавливался на первой ссылке из группы появившихся элементов на странице.
Правки в рамках #1068.

Поправляет порядок фокуса при взаимодействии с кнопкой «Показать ещё» (главная, 404)

---

src/libs/github-contribution-service/github-contribution-service.js
src/scripts/modules/filter-panel.js
src/scripts/modules/search-page-filter.js
src/styles/blocks/people-page.css
src/styles/blocks/search-page.css
src/views/people.njk
src/views/search.njk

Сейчас на мобильниках выпадающие меню с фильтрами по разделам на страницах поиска и участников располагаются под меню из-за более низкого `z-index` у них. Особенно хорошо это заметно, когда на странице немного контента.
Так что я задала более высокое значение для дропдаунов с фильтрами.
Вторая доработка — то, как изменяется название кнопки при взаимодействии с ней. Сейчас кнопка называется всегда «Показать/скрыть фильтр». В этом ПР я изменяю её название динамически в зависимости от того, открыт дропдаун или нет.
Третья доработка — `aria-expanded` у кнопки. Так как она что-то показывает и скрывает, хорошо это свойство обозначить и на уровне кода. `aria-controls` решила не добавлять, так как у атрибута так себе поддержка. Можно добавить, если она расширится.

Исправляет раскрывающиеся меню с фильтрами по разделам (поиск, участники)

---

src/includes/blocks/person-avatar.njk

Кажется, что изображения на странице со всеми участниками декоративные. Даже если мы хотим оставлять описание картинок на этой странице, то сейчас оно некорректное. В нём есть слово «изображение» и оно никак не описывает картинку, к сожалению.
Если решим дать авторам возможность описывать свои аватарки в их профилях, то можно будет использовать это же описание на странице со всеми людьми.
ПР закрывает #1079.

Разбирается с `alt` на странице всех участников

---

src/includes/blocks/search-category.njk

На странице поиска сейчас у <fieldset> с фильтрами нет лейбла, который был бы доступен для скринридеров.
```html
<fieldset class="search-category">
<legend class="visually-hidden" aria-hidden="true">Фильтровать по:</legend>
<div class="search-category__legend">Фильтровать по:</div>
…
</fieldset>
```
Я просто убрала из тега `<label>` атрибут `aria-hidden="true"` и, наоборот, добавила его к `<div>`, который визуально отображается на странице.
ПР закрывает #1055.

Улучшает разметку фильтров по разделам (поиск)

---

src/libs/github-contribution-service/github-contribution-service.js
src/styles/blocks/header.css
src/styles/blocks/person-badges.css
src/styles/blocks/person-page.css

Приветствую! 🖖
1) Заметил, что на участнике [Ольга Алексашенко](https://doka.guide/people/tachisis/) появляется нижний скролл на разрешениях **768-976px** и **1024-1221px**.
____
2) Также, **на блоке с ачивками** у участника [Алёна Батицкая](https://doka.guide/people/solarrust/) (по крайней мере во время отладки) - ачивки решили наложиться друг на дружку. 
____
3) Последний момент - это на разрешении **1440px+** происходит уменьшение ширины общего блока для имени, описания и колонок со списками, где участник является автором или редактором.
Мне показалось это странным поведением, поэтому решил оставить одну ширину общего блока - **ДО 1440px**. 
Проблемы все исправлены 😉

Корректирует адаптивную вёрстку на странице профиля участника

---

src/styles/blocks/search-hit.css

Решение по теме #1056
Проблема возникает, поскольку по поиску ключа `DOM`  среди выдачи в строке `document.addEventListener('DOMContentLoaded',` браузер не находит пробелов для разбивки предложения, из-за чего возникает переполнение. Иных правил не задано. В тоже время внутри заголовка `search-hit__title` работает правило `word-break: break-word`.
Предлагаю добавить для контента выдачи правило на случай переполнения в лице `overflow-wrap: anywhere`.

Устраняет горизонтальный скролл на странице поиска

---

src/scripts/modules/copy-code-snippet.js
src/transforms/article-code-blocks-transform.js

Исправила две вещи в рамках ишью #1072: теперь скринридер объявит о новом имени кнопки при удачном/неудачном копировании кода и при окончании таймаута, а ещё фокус вернётся на кнопку после того, как она снова станет активной без атрибута `disabled` (если не перешли к другому элементу).
Без этих изменений в скрипте фокус сбрасывается с кнопки после того, как она какое-то время была неактивна. Если не перешли к следующему элементу, а остались на кнопке, фокус пропадает и из-за этого не особо понятно, где окажешься после таба.

Улучшает сообщение о скопированном коде

---

src/includes/blocks/linked-article.njk
src/scripts/modules/linked-article-navigation.js

Привет! 
Проблема: навигация между статьями через `alt + стрелка` немного забагована, возникает перескакивание через статью. 
Система на Win11, тестил в Хроме, Яндексе, Firefox.
Это объясняется тем, что у браузеров стандартное поведение на `alt + стрелка` это перейти назад/вперед по истории, из-за чего браузер, в случае стрелки влево, сначала возвращает к прошлой статье, а потом обработчик на `keyup` дополнительно откатывает на материал ещё назад.
https://support.google.com/chrome/answer/157179?hl=ru-ru&co=GENIE.Platform%3DDesktop
https://browser.yandex.ru/help/useful-features/hotkeys.html
https://support.mozilla.org/ru/kb/sochetaniya-klavish
Предлагаю поменять `alt` на универсальный `ctrl`, он не занят у браузеров навигацией, и одновременно этим вернуть `alt` стандартное поведение. …

Меняет клавиши навигации

---

src/includes/blocks/person-avatar.njk
src/views/person.11tydata.js
src/views/person.njk

Чтобы сделать интерфейс доступнее делает возможность заполнить альтернативное описание аватарки на странице пользователя. Важно: на страницу со списком пользователей такое описание не пробрасывается.
Для того, чтобы проверить, переключитесь на [PR #4345](https://github.com/doka-guide/content/pull/4345) в контенте.
Было:
Стало:
В meta на странице пользователя надо добавить опциональный параметр: `photoAlt`, чтобы аватарка получила альтернативное написание. Если параметра не будет, то и описания не будет.

Добавляет альт в аватарку при его наличии

---

src/scripts/modules/toc.js

Исправляет #1121
Не уверен, что это адекватное решение, но сделал так потому что после копирования:
1. В Chrome и FF `document.activeElement` - это `body`
2. В Safari - остаётся кнопка
cc @TatianaFokina

Исправляет фокус после копировании ссылки на раздел

---

src/styles/blocks/articles-group.css

Всегда хотелось «отлепить» иконку карандаша от заголовка статьи, визуально выглядит некрасиво) Предлагаю добавить чуть-чуть расстояния.
Было:
Стало:
Тем более внутри статей такой gap есть:

Добавляет пространство к иконке карандаша

---

src/scripts/modules/toc.js

Привет! Заметил недавний PR #1122 по ишью #1121, не уверен, что это лучшее решение.
Во-первых, активный элемент после нажатия — это `body`, поэтому не понятно, зачем условие `document.activeElement === button`, а в Safari фокус и так сам вернётся на `button`;
Во-вторых, если скопировать одну ссылку, а потом сразу табнуть (сценарий: передумать) на другую и скопировать ее, то фокус вернется на первую, а должен остаться на второй. Так происходит, потому что фокус в этот момент уже не на `body`, поэтому блок `if` игнорируется.
Предлагаю такое решение: просто смотреть, есть ли параллельное копирование. Если нету, то фокус восстанавливаем обычно, если есть, то игнорируем установку фокуса до последней нажатой кнопки.

Восстанавливает фокус после копирования ссылки

---

src/includes/blocks/search.njk
src/scripts/modules/search.js
src/views/search.njk

Пулреквест закрывает два ишьюз: #1115 и #1077.
- Добавила скрытый `<h1>` с текстом «Результаты поиска».
- Связала `<main>` с этим скрытым заголовком, чтобы пользователи скринридеров знали, как эта область называется и могли быстро переместиться к результатам поиска.
- Сделала ссылки из списка с выдачей `<h2>` вместо `<h3>`.
- Связала текст «Введите что-нибудь в поле для начала поиска» с полем поиска с помощью `aria-describedby`.
- Изменила текст подсказки на «Введите что-нибудь в поле для начала поиска, после этого появится результат».
- Сделала пустую выдачу интерактивной областью, задав элементу с классом `.search__output` атрибуты `aria-live="assertive"` и `aria-atomic="true"`.
Я прочитала, что с точки зрения UX не ок постоянно объявлять результаты выдачи в случае динамического поиска. …

Добавляет live region и правильные заголовки на страницу поиска 

---

src/includes/blocks/header.njk
src/scripts/modules/header.js
src/styles/blocks/header.css
src/views/index.njk

Решает #985.
Исправления на главной:
- меню всегда открыто и у него `position: relative`;
- скрыто первое меню с помощью `display: none`;
- нет кнопки для закрытия меню;
- при скролле наверх меню не появляется.
На других страницах `visibility: hidden` использую потому, что нам бы его всегда скрывать, когда открывается второе меню. Тогда на пунктах в нём нельзя будет зафокуситься. При этом мы сохраняем его высоту и из-за этого контент на странице не скачет туда-сюда при открытии меню, когда скролишь вверх.
Что осталось исправить и с чем нужна ваша помощь:
Она есть только в Vivaldi, остальные браузеры ведут себя адекватно! Проверьте, пожалуйста, на всякий случай в Safari и в каком-нибудь Chrome на MacOS. Особенно когда используешь клавиатуру для навигации.
В Chrome всё выглядит хорошо (как …

Исправляет поведение меню на главной

---

src/styles/landing.css

Фиксит перенос заголовка для Firefox

---

src/includes/questions.njk
src/styles/blocks/answer.css
src/styles/blocks/questions.css

Судя по статистике, у нас сейчас 0 переходов на сайт партнёра с этой плашки. При этом она занимает место и снижает привлекательность этой рубрики для потенциальных контрибьюторов. У кого-то могут быть личные консёрны по поводу своего имени под упоминанием определённого бренда.
Предлагаю совсем убрать этот текст, облегчив тем самым интерфейс и повысив привлекательность отвтетов на вопросы в этой рубрике.

Убираем текст в начале раздела «На собеседовании»

---

config/constants.js
src/includes/blocks/footer.njk

На текущей сборке спецпроектов есть проблема в подвалах — битые ссылки.
Можно решить это двумя способами:
1. Быстрый: Поправить ссылки в конкретном спецпроекте
2. Подольше: Добавить в основную ветку, а потом и в ветку текущего спецпроекта условие проверки на URL, и вывода нужного результата.
В этом PR быстрый метод, но я могу переделать его в тот, что подольше.
Плюсы:
- Ссылки в подвале починены и работают
- Появилась ссылка на основную Доку
Минусы:
- Из Доки на спецпроект вернуться нельзя

Правит ссылки в подвале

---

.eleventy.js
package-lock.json
package.json
src/includes/blocks/baseline.njk
src/styles/blocks/baseline.css
src/styles/index.css
src/views/doc.11tydata.js
src/views/doc.njk

Заверстала блок для вывода данных о поддержке браузерами фичи. 
Выглядит пока так 
Выбрала «компактную» форму. Стащила с web.dev. «Официального» виджета пока нет. Верстают кто как.
В текущем варианте видно все 4 возможных статуса поддержки: 
- Поддерживается
- Не поддерживается
- За флагом
- В превью
Оставила ссылочку на страницу описания проекта чтобы у людей не было вопроса откуда инфа.
Чтобы потестить пока что можно добавить любой статье тег baseline. Виджет будет внизу страницы, под подсказками.

Приносит виджет Baseline

---

src/styles/blocks/logo.css

Убирает отступ снизу в логотипе 404-й страницы, чтобы лого везде был одинаковым.
Было:
Стало:
Для теста добавьте к адресу любой страницы на превью и на проде в URL: 404

Fix: убирает отступ в лого на 404 странице

---

src/styles/code-dark-theme.css
src/styles/code-light-theme.css

Исправила небольшие проблемы с контрастностью, описанные в ишью #1059.

Улучшает контрастность цветов в примерах кода

---

src/transforms/headings-anchor-transform.js

Решение в рамках ишью #1149. Пропустила, что у `aria-describedby` одинаковые значений, а это критическая ошибка. Для уникальности значения просто добавляю к `status` такой же текст, как у заголовков.

Делает `id` у кнопки копирования секции уникальным и изменяет её текст

---

src/includes/blocks/linked-article.njk
src/views/doc.njk

Решила проблему, описанную в ишью #1150. Теперь у всех трёх `<aside>` на странице есть скрытое имя. По правилам у повторяющихся ориентиров должно быть уникальное имя, чтобы пользователи вспомогательных технологий, открыв меню с ними, быстро смогли сориентироваться между одинаковыми.

Добавляет `aria-labelledby` для `<aside>` на странице материала

---

src/styles/blocks/content.css

Добавила отступ между параграфами в блочных цитатах такого вида:
```
> Я блочная 
> цитата
> 
> Я её автор, например
```
Пока сделала такого же размера, как отступ между параграфами в `<aside>`, чтобы не выбивалось.
Соседний ПР [#17](https://github.com/doka-guide/landings/pull/17)

Добавляет отступ между параграфами для блочных цитат

---

src/styles/blocks/doc.css

Небольшой пиар, который исправляет проблему со стилями из #1111.
Теперь на мобилках у блока с рекомендуемыми статьями есть отступы.

Добавляет отступы для блока с рекомендуемыми статьями

---

src/styles/blocks/content.css

Мне давно мазолит глаза то, что у нас для `<kbd>` используется шрифт по умолчанию. Вот поменяла.
@skorobaeus, если хочешь ещё как-то дополнительно стилизовать тег, можешь смело добавлять стили сюда.

Добавляет правильный шрифт для `<kbd>`

---

src/styles/blocks/hotkey.css
src/styles/blocks/linked-article.css

Решила проблему в рамках #1066.
Обнаружила, что цвет в них задаётся не только с помощью цвета как у текста, но и благодаря `opacity`. Так что просто понизила прозрачность на 10%. В итоге получились цвета `#68696c` в светлой теме и `#bfc0c1` в тёмной.
Можно попробовать подобрать так цвет, который предлагала Света, но, кажется, на это уйдёт больше времени. А цвета, которые у меня получились, соответствуют минимальному уровню контрастности.

Улучшает контрастность клавиатурных сокращений

---

src/includes/blocks/baseline.njk
src/styles/blocks/baseline.css

По мотивам ишью #1143. Смотреть можно в [доке про `grid-area`](https://platform-1187.dev.doka.guide/css/grid-area/).
Что исправила:
- убрала лишние ARIA-атрибуты и `title` из `<span>`, скрыла повторяющуюся инфу от скринридеров;
- слегка изменила скрытый текст (убрала заглавную букву, так как это всё одно предложение);
- вернула классы на место в одном `<span>`;
- использовала наш цвет для текста и пофиксила проблемы с контрастностью;
- слегка изменила способ задавания отступов, пофиксила лишний на мобилках и планшетах;
- добавила отступ ко всему блоку.
<s>Остался только один вопрос: в итоге мы планируем делать «Поддержка в браузерах» заголовком или нет? Если да, нужна ваша помощь, чтобы заголовок не попадал в оглавление статьи.</s>

Улучшает блок с Baseline

---

src/views/person.11tydata.js

Возникала ошибка с выводов советов и ответов на странице участника в том случае, если категории материалов, над которыми работал участник не совпадали с категориями ответов и советов.
Пример страницы участника на сайте:
https://doka.guide/people/ra1nbow1/
хотя ответ есть в:
https://doka.guide/a11y/chto-takoe-a11y/#matvey-romanov-otvechaet
Ссылка участника в превью для проверки:
[/people/ra1nbow1/](https://platform-1189.dev.doka.guide/people/ra1nbow1/)

Меняет вывод советов/ответов на странице автора

---

src/includes/blocks/linked-article.njk
src/libs/heading-hierarchy/heading-hierarchy.js
src/views/doc.njk

Решаю задачу из #1153 и не только.
Что изменилось?
- Сделала оглавление ориентиром `complementary`.
- Объединила в один `<aside>` следующую и предыдущую статьи.
- Добавила подпись к ориентиру `banner` на странице материала.
- Добавила подпись к ориентиру `contentinfo` на странице материала.
- Все подписи добавила через `aria-label`.
Теперь в списке всех ориентиров на странице стало удобнее разобраться (на примере NVDA). Когда несколько одинаковых ориентиров на странице, бывает сложно понять, что в них содержится. Поэтому их рекомендуют подписывать в этом случае.

Разбирается с ориентирами страницы материала

---

src/scripts/modules/header.js
src/styles/blocks/article.css
src/styles/blocks/header.css

- Уменьшил время анимации, с 600 миллисекунд до 200, для шапки и бокового меню статьи. Значение в 300 миллисекунд, как предлагали в issue, показалось медленным, а моё в 125 - чересчур быстрым.
- Для появления фиксированной шапки при скролле наверх нужно прокрутить страницу минимум на 180 пикселей - мне это расстояние кажется комфортным для использования на телефоне и десктопе и в то же время не ломающим логику наличия фиксированной шапки.

Исправляет проблему медленной и постоянной анимации фиксированной шапки при скролле.

---

src/includes/feedback-form.njk
src/scripts/modules/feedback-form.js
src/styles/blocks/feedback-form.css
src/styles/blocks/text-control.css
src/styles/blocks/vote.css

Исправления в рамках #1067 и #1071.
Что изменилось:
- перенесла «Спасибо» из заголовка под поле с оценкой, заменила текст на «Спасибо за оценку ❤️»;
- изменила текст ошибки с «Во время отправки формы что-то пошло не так. Попробуйте ещё раз?» на «Во время отправки формы что-то пошло не так. Перезагрузите страницу и попробуйте оценить материал ещё раз»;
- теперь заголовок групп кнопок постоянно «Статья была полезной?», сделала его `<legend>`;
- связала статус об успешной отправке и ошибку с `<form>` с помощью `aria-describedby` и live region;
- навесила на `<fieldset>` атрибут `inert` вместо `disabled` (`disabled` нельзя задавать группам элементов, только одному интерактивному);
- убрала автоматический перенос фокуса на текстовое поле (так не очень хорошо делать в формах);
- добавила лейбл …

Улучшает кнопки для оценки материала

---

src/scripts/modules/subscribe-form.js
src/styles/blocks/subscribe-page.css
src/transforms/headings-anchor-transform.js
src/views/subscribe.njk

Решаю проблемы из комментария к #1172 и не только. Окно подписки не трогала, хотя проблема с ним была описана изначально.
Что исправила [на странице подписки на рассылку](https://platform-1188.dev.doka.guide/subscribe/):
- добавила атрибуты `required`, `pattern` и `autocomplete` для поля с почтой;
- добавила тексты ошибок для разных статусов (успех, ошибка, прогресс) для обеих форм, сделала их live regions;
- добавила стили для ошибок и других статусов;
- связала тексты ошибок с формами с помощью `aria-describedby`;
- добавила `outline-offset` для кнопок, а то при фокусе рамок вообще не видно;
- немного переписала тексты;
- поправила уехавшую влево кнопку «Подписаться» в Firefox;
- перекрасила прогрессбар (раньше был белым на светло-сером фоне), отключила его, когда отключена анимация в …

Улучшает форму подписки на рассылку

---

src/libs/github-contribution-service/github-contribution-service.js
src/views/person.11tydata.js

Заметил что в граф запросе для получения данных о дате пуша используется поле `pushedDate` - судя по [документации](https://docs.github.com/en/graphql/reference/objects#commit) оно больше не поддерживается (в запросах возвращает null), заменил его на поле `committedDate` - как я понимаю оно тоже подходит так как наличие коммитов проверяется в `defaultBranchRef`, которая является веткой main. 
Из-за наличия кеша может отдавать старые данные - нужно сбросить кеш или дождаться пока он протухнет (судя по коду время жизни сутки)
Closes #1205

Изменил поле pushedDate в граф запросе на получение информации о коммите

---

src/sw.js

По результатам тестирования стало понятно, что надо изменить следующее:
1. Добавить в кеш манифест.
2. Убрать предварительную обработку (возврат пустых ответов) для POST-запросов.
3. Убрать предварительную обработку (возврат пустых ответов) для GET-запросов.
4. Убрать отсылку запросов на сторонние ресурсы.
5. Изменить стратегию кеширования — сначала запрашивать ресурсу из сети, а потом уже запрашивать ресурс из кеша. Это нужно для получения максимально актуальной версии ресурсов, при это не экономя трафик.

Первая серия изменений PWA

---

src/styles/blocks/answer.css
src/styles/blocks/practices.css

**Что происходит**
Этот ПР фиксит вот эти маленькие пустоты в уголках практик и советов:
**Где посмотреть**
Развернуть практику или совет на любой странице, где они есть, например "Функция" ([платформа](https://doka.guide/js/function/) / [превью](https://platform-1244.dev.doka.guide/js/function/)), промотать вниз. Левый и правый нижний угол.

Микрофикс рамок у практик и советов

---

package.json

Существует проблема нехватки памяти для сборки Доки локально, описанная в #1231. Данный пиар решает эту проблему.
Другие проблемы, описанные в #1231, решены на предыдущих итерациях.

Добавляет памяти

---

src/styles/blocks/footer.css
src/styles/blocks/link.css

- Возвращает ховер-эффекты ссылкам в хэдере;
- Возвращает подчёркивания заголовкам разделов в нижней секции;
- Заодно убирает подчёркивания у ссылок на соцсети, потому что они странно выглядят;
- (пересортировывает правила, потому что линтер заставил).

Чинит оформление ссылок на главной

---

package-lock.json
package.json

Текущая версия пакета [web-features](https://github.com/web-platform-dx/web-features/releases/tag/v0.8.6) - 0.8.6 
включает много нового.
Например? у меня есть PR с доками по новым методам Set:
- https://github.com/doka-guide/content/pull/5400
- https://github.com/doka-guide/content/pull/5401
- 
я добавил там данные о baseline. С используемой версией 0.5.0 выглядет не очень:
Предлагаю обновить версию web-features

Поднимает версию web-features

---

gulpfile.js

Исправляет проблему с генерацией og-картинок для материалов с иллюстрациями

---

.eleventy.js
package-lock.json
package.json

В текущей используемой версии 0.86 есть проблемы с отображением версии Firefox для новых методов `Set`.
Например:
doka.guide/js/set-union/
| main | PR |
|--------|--------|
| ![изображение](https://github.com/user-attachments/assets/bd43a68c-ef73-4940-965b-444e88593c09) | ![изображение](https://github.com/user-attachments/assets/d3289286-bf73-40a7-9932-ca419178e490) | 
Этот PR:
- Поднимает версию до 1.0.0
- Исправляет импорт из модуля `web-features`.
FYI: Начиная с версии 0.10 (предпоследний релиз) требуется использовать именованый импорт вместо дефолтного.
см: https://www.npmjs.com/package/web-features/v/0.10.0
https://github.com/web-platform-dx/web-features/releases/tag/v0.10.0

Поднимает версию web-features до 1.0.0

---

src/styles/blocks/base.css

Close #1282 
Сделала `.body__base` гридом с нужными размерами колонок и минимальной высотой в `100dvh`. Теперь даже на «коротких страницах» футер прибит. Потестила на всех подвернувшихся страничках. Буду благодарна, если вы тоже посмотрите.
Превью (смотреть на маленьком масштабе для наглядности): https://platform-1283.dev.doka.guide/newsletters/

Прибивает подвал

---

.eleventy.js
package-lock.json
package.json
src/scripts/modules/transform-article-data.js
src/views/doc-json.11tydata.js
src/views/doc.11tydata.js
src/views/views.11tydata.js

Сделал то, что давно уже надо было (из серии TODO)

Выносит функцию в отдельный модуль

---

src/scripts/modules/transform-article-data.js

Упрощает xот-фикс для картинок на главной. см: https://github.com/doka-guide/platform/commit/4f92d3d8ec74a33a8019c6a09835439c90849a25
Задача: получить поле(строку) `article.data.cover.mobile`
Необходимо:
- убедиться что `article.data.cover` существует и является объектом
- получить значение поля `mobile` и вернуть его
- иначе, вернуть `undefined`
Для этого можем использовать оператор `?.`
`article.data.cover?.mobile` - вернёт `undefined` если:
- `cover` не содержит `mobile`
- `cover` не является объектом
тесты:
```js
function imageLink() {
return this.cover?.mobile
}
console.log(imageLink.call({ cover: { mobile: 'image' } })); // image
console.log(imageLink.call({ cover: {} })); // undefined
console.log(imageLink.call({ cover: [] })); // undefined
console.log(imageLink.call({ cover: 'str' …
```

Упрощает получение значение свойства `article.data.cover.mobile`

---

src/styles/blocks/header.css

Потестите все, пожалуйста, всё ли ок сейчас в Safari и Firefox: и на десктопе, и на мобилках для верности. Дропдаун не должен убегать от меню при скроле вниз.

Фиксирует меню так, чтобы всё работало как надо

---

src/scripts/modules/header.js
src/scripts/modules/search.js

После мержа `Рефакторинг меню (#1191)` появились следующие сложности:
- нажатие `/` (или `NumpadDivide`) не приводит к активации Поиска. Открывется встроенный поиск FF. (1)🔴 
- нажатие `/` (или `NumpadDivide`) не приводит к активации Поиска. (2)🔴 
Причины:
1. В коде `scripts/modules/header.js` нет обработчика `keydown` для подавления показа встроенного поиска FF (см. 1)
2. В коде `scripts/modules/search.js` в обработчике `keyup` нет кода для активации фокуса в строке поиска (см. 2)
@TatianaFokina , @skorobaeus посмотрите пожалуйста )

Исправляет обработку перехода к поиску по клавише '/'

---

src/styles/blocks/header.css

Исправляет проблему скрытой строки поиска для экранов с размерами: 768px < size < 1024px
main:
Fix:
@TatianaFokina, ещё патч !

Показывает строку поиска для средних экранов

---

src/views/person.njk

Ошибка:
Допустим вклад участника в какой-либо раздел (HTML, CSS, и тп) это **только ответы на вопросы собеседования** (см. isOnlyWithAnswer() в файле person.11tydata.js)
В этом случае разметка списка для этой категории включает цикл по ответам участника (answersInArticles) состоящим из `<ul>`. Так как сами `<ul>` образуют список, требуется родительский элемент для установки отступов между ними.
Та же ситуация произойдёт если вклад участника в какую-либо категорию это  **только советы** (см. isOnlyWithPractice() в файле person.11tydata.js)
Исправляет: #1234
Доп. тестовая страница для примера: `/people/vitya-ne/` (см. вклад в раздел "Веб-платформа")

Исправляет разметку списка ответов на странице участника

---

src/styles/blocks/intro.css
src/views/index.njk

Было:
Стало:
Мерджить вместе с [#5497](https://github.com/doka-guide/content/pull/5497).

Меняет партнёрский блок

---

src/views/doc.11tydata.js

Корректирует получение флага `isLong`, определяющего что контент совета большой и его нужно показывать с кнопкой "+ Развернуть".
Перед подсчётом абзацев я откидываю пустые.
Текущий подход основанный на подсчёте абзацев (>2) не учитывал пустые абзацы как тут:
[Совет Алёны про outline — Прод](https://doka.guide/css/outline/#alyona-batickaya-sovetuet) || [Совет Алёны про outline — Превью](https://platform-1303.dev.doka.guide/css/outline/#alyona-batickaya-sovetuet), вот его код:
https://github.com/doka-guide/content/blob/main/css/outline/practice/solarrust.md?plain=1
Как оказалось "коротких" советов довольно много.
Я пробежася по нескольким  и убедился что карточка совета не занимает слишком много места.
Однако возможна ситуация (теоритически) когда совет - один очень большой абзац. Возможно …

Корректирует определение 'длинного' совета

---

src/styles/blocks/breadcrumbs.css
src/styles/blocks/header.css

Если в конце названия статьи есть эмодзи, то ее правая часть обрезается в breadcrumbs в режиме прокрутки страницы.
Это видно в разделах спец проекта "[Трудоустройство](https://dream-job.doka.guide/dream-job/)".
**PS**: Ветка для проекта "Трудоустройство" [эта](https://github.com/doka-guide/platform/tree/landings-dream-job)? Туда нужно будет тоже влить правки.

Корректирует отображение эмодзи в breadcrumbs

---

src/styles/blocks/header-button.css
src/styles/blocks/header.css
src/styles/blocks/hotkey.css

Заметил несколько странностей в стилях при использовании поиска не на главной странице:
1. Артефакт хоткей-кнопки при фокусе на поиске с разрешением x: 768px <= x <= 1024px
2. Иконка ✖️частично перекрывается при скроле на нескольких разрешениях
3. Меню наползает на заголовок в режиме поиска на разрешении >= 1680px
Мой PR исправляет эти странности.
Тестировал в FF и Chrome на ноуте с Win 10. Экран: 1920x1080 масштаб 125%

Исправляет стили заголовка

---

.github/workflows/product-deploy.yml
gulpfile.js
package-lock.json
package.json

В этом пиаре удаляется этап подготовки карточек для социальных сетей, поскольку мы переходим на другие рельсы.

Удаляет этап генерации карточек для социальных сетей

---

src/includes/blocks/baseline.njk
src/styles/blocks/baseline.css
src/views/doc.11tydata.js

Сейчас, если фича поддерживается не всеми браузерами, baseline отображается так:
Я предлагаю исправить и отображать так:
ПР:
- исправляет формирование объекта `baseline.supported`. 
- исправялет отображение

Исправляет отображение baseline

---

src/scripts/modules/person-badges.js

В консоль падает ошибка про чтение координато значка.
Добавила проверок, чтобы все данные точно были. Локально ошибка пропала.

Фиксит ошибку чтения координат значка

---

.github/workflows/linting.yml
.github/workflows/pr-preview.yml

Линтер ломается с ошибкой, ругается на старую версию пакета с кэшем
Поменяла версию на 4.

Обновляет версию пакета actions/cache@v4 для экшенов

---

package-lock.json
package.json

Обновляет версию web-features.
Текущая версия (2.22.0) пакета `web-features` содержит устаревшие данные.
Например:
[Поддержка атрибута `inert`](https://web-platform-dx.github.io/web-features-explorer/features/inert/) уже есть во всех браузерах:
а с текущей версии пакета:

Поднимает версию web-features до 2.40.2

---

src/scripts/core/search-api-client.js

Правки:
1. Удаление настроек по умолчанию для Algolia, которая давно не используется
2. Использование http-метода `GET` вместо `POST`, так как лучше подходит по своей семантике получения данных и добавляет возможность кэширования результатов поиска в будущем
3. Удаляет задание заголовка `Origin`, так как его перепишет браузер на действительный
4. Упрощает сериализацию url в строку: знак `?`  будет проставляться сам

Рефакторинг класса `SearchAPIClient` для поиска
