Dockerfile
=> Уменьшает количество слоев

.gitignore, make-links.js, src/people/ezhkov/index.md, src/people/nlopin/index.md, src/people/pepelsbey/index.md, src/people/solarrust/index.md
- Удаляет из репозитория папку Люди, она будет находиться [в контентном репозитории](https://github.com/Y-Doka/content) и подключаться при сборке. 
- Добавляет симлинки для подключения папки Люди снаружи.
=> Удаляет папку people

src/layouts/base.njk
Добавляет `title` из статьи в `<title>` с сохранением названия ресурса.
=> Правит заголовок

package-lock.json, package.json
Модуль `esbuild` не был установлен, установил.
=> Добавляет необходимый модуль

.eleventy.js, .env, Dockerfile, config/constants.js, make-links.js, package-lock.json, package.json, utils/sections.js
Была идея вынести список папок, в которых находятся статьи в отдельный конфигурационный файл. 
Чтобы подключить этот файл , используется
```js
const sectionsAll = require("./utils/sections.js")
let sections = sectionsAll.sectionsAll;
```
=> Создаёт файл настроек

src/includes/contributors.njk, src/layouts/aside-page.njk
Мы, вроде бы договорились, что у статьи один автор, а остальные контрибуторы? Если да, то вот вывод данных.
=> Добавляет контрибуторов

.eleventy.js, src/includes/practices.njk, src/layouts/aside-page.njk
Добавил мнения авторов на основании урла статьи, и поскольку иначе надо было обосновать блок «В работе», а у меня не получилось убрать этот блок, если мнений авторов нет, сделал призыв такие мнения оставить. Это позволит развивать проект. 
Если практики есть
Если практик нет
Затем надо будет поменять юзернейм на другую часть, как будет подключена папка people
=> Добавляет блок с практиками

.env, .gitignore, src/includes/footer.njk, src/layouts/page.njk
- Переносит статью О проекте
- Добавляет оформление в 'page.njk'
- Добавляет нужные переменные
[Пул-реквест в контенте](https://github.com/Y-Doka/content/pull/354)
=> Переносит статью О проекте

src/includes/aside.njk, src/styles/blocks/aside.css
Немного правит стили в асайде, потому что они немного сломались. 
Применять после #84
=> Правит стили в асайде

src/scripts/index.js, src/scripts/modules/aside.js, src/styles/blocks/aside.css, src/styles/pages/aside-page.css
- Возвращает скрытие и показ асайда
- Скрипт по показу актуального модуля не перенесён, потому что можем начать править блоки.
- Добавляет немного анимации
Мы сейчас начинаем готовить работу именно через контентно-платформенную связку, авторам и контрибуторам будет удобнее, если асайд будет скрываться.
=> Возвращает скрытие и показ асайда

.eleventy.js
=> Добавляет шорткод

src/layouts/article.njk
=> Добавляет обложки

CODEOWNERS
Кажется, мы забыли добавить @tachisis в качестве редактора, в главный ридми-файл
=> Добавляет редактора в главный ридми

CODEOWNERS
Я пока не нашёл явных оунеров частей кода — платформу мы разрабатываем общими силами.
Но документация и ридми — это для Оли. Потом можно будет добавлять и выделять какие-то участки, когда всё сложится.
=> Упрощает оунерство

.github/workflows/netlify-deploy.yml, README.md
[Как в контенте](https://github.com/Y-Doka/content/pull/820), только меньше медалей.
=> Добавляет в ридми бейдж со статусом деплоя

src/includes/meta.njk
=> Не выводит название проекта на главной

.eleventy.js, src/layouts/article.njk
- Добавляет шорткод, который показывает, как давно отредактирована статья.
=> Добавляет переменную для обозначения последнего редактирования статьи

.eleventy.js, src/pages/sitemap.xml.njk, src/robots.txt
Добавил самые простые варианты файлов для затравки. Предлагаю развить эту тему в этом PR.
Для Algolia подойдёт и такой вариант `robots.txt`.
@pepelsbey, @nlopin, @furtivite, @solarrust помогайте 😇
=> Штуки для поиска и SEO

src/views/doc.11tydata.js
FIx [231](https://github.com/doka-guide/platform/issues/231)
=> Правит вывод авторов

.github/workflows/docker-deploy.yml, README.md
В связи с переходом на аккаунт организации во избежания оплаты Docker завёл такой вот экшен. Надо протестировать, насколько он хорош.
=> Добавляет экшн для сборки образа

.eleventy.js
Проверяем сломается ли action
Словили [ошибку](https://github.com/doka-guide/platform/actions/runs/1026293308) по следам #253
=> Правит скрипт для путей

README.md
Чтобы было так же красиво, как в контенте.
=> Выравнивает шильдики

.eleventy.js, .eslintrc.json, .gitignore, src/scripts/index.js, src/scripts/modules/last-update.js, src/views/doc.11tydata.js, src/views/doc.njk
С задачей связан [PR для контента](https://github.com/doka-guide/content/pull/1097)
=> Вывод даты последнего редактирования статьи

.eleventy.js
=> Исключает файлы индексов категорий из коллекции статей

.eleventy.js, src/includes/contributors.njk, src/views/doc.11tydata.js
=> Выводит всех людей, причастных к статье

src/views/doc.njk
=> Добавляет вывод обложек для статей

.eleventy.js, .eslintignore, .gitignore, package-lock.json, package.json
Пока это черновик, так как нужно знать, какие размеры будут у изображения и какие форматы использовать.
Дополнительно заменил html-минификатор на [htmlnano](https://github.com/posthtml/htmlnano), так как он лучше распознает неэкранированные сущности. Возможно, эту операцию стоит перенести в gulp-задачу.
=> Замена img на picture внутри контента

gulpfile.js, package-lock.json, package.json
Во время сборки пути до стилей и скриптов преобразуются с помошью регулярок, что затрудняет понимание процесса сборки.  Предлагается сохранять структуру путей.
=> Удаляет преобразование путей во время сборки

.eleventy.js, src/views/doc.njk
Обычно люди читают около 120-180 слов в минуту. Это в среднем. Есть малоинформативная [ссылка](https://ru.wikipedia.org/wiki/Скорочтение) на Википедии.
=> Добавляет расчёт времени чтения статьи

src/styles/blocks/logo.css
=> Включает специальное отображение логотипа

.github/workflows/surge-preview.yml
По опыту репозитория с контентом в PR предлагается использовать другой способ формирования комментария.
=> Улучшает превью

.eleventy.js, package-lock.json, package.json, src/transforms/code-transform.js
- Правка бага с клонированием узла
- Явные названия переменных для элементов _pre_ и _code_
- Обновление библиотеки LinkeDOM
=> Правки для трансформаций блоков кода

.eleventy.js, src/styles/blocks/breadcrumbs.css, src/styles/blocks/featured-article.css, src/styles/blocks/link.css, src/styles/blocks/logo.css, src/transforms/code-transform.js, src/transforms/demo-link-transform.js, src/transforms/headings-transform.js, src/transforms/image-transform.js, src/transforms/link-transform.js, src/transforms/toc-transform.js
- на ссылки внутри контента добавляются классы через трансформации, чтобы не дублировать стили - `.content a, .link {}`
- добавлен API для управления толщиной подчёркивания ссылки
=> Стилизация ссылок внтури контента

src/styles/blocks/article-heading.css, src/styles/blocks/article.css, src/styles/blocks/code-block.css, src/styles/blocks/code.css, src/styles/blocks/content.css, src/styles/blocks/standalone-page.css, src/styles/index.css, src/transforms/code-transform.js, src/transforms/headings-transform.js
Добавляет стили для:
- инлайн-блоки с кодом
- отступы для заголовков, параграфов
=> Базовая стилизация контента

src/views/sitemap.11tydata.js, src/views/sitemap.njk
=> Вариант починки рендера `sitemap.xml`

.eleventy.js, src/styles/blocks/code-block.css, src/styles/blocks/format-block.css, src/styles/index.css, src/transforms/code-transform.js
=> Разделение блоков кода от преформатированного текста

src/transforms/image-transform.js
Правки для генерации картинок в контенте:
- Поправлен атрибут `sizes`
- Все настройки вынесены в объект `config` вверху файла `image-transform.js`
=> Уточнение размеров картинок для генерации

.github/workflows/surge-preview.yml, .github/workflows/w3c-validator.yml, README.md
Необходимо валидировать HTML в готовой сборке сайта для семантики и чтобы было всё правильно. Среди решений есть несколько. По результатам данный вариант работает быстрее всего и при этом выдаёт правильный результат.
=> Добавляет валидатор w3c

src/transforms/code-transform.js
=> Подключает все языки для hightlight.js

src/includes/meta.njk, src/libs/title-formatter/title-formatter.js, src/views/404.11tydata.js, src/views/404.njk, src/views/all.11tydata.js, src/views/all.njk, src/views/article-index.11tydata.js, src/views/doc.11tydata.js, src/views/index.11tydata.js, src/views/page.11tydata.js
=> Задаёт нужный формат тега `<title />` для каждой страницы

src/includes/blocks/footer.njk, src/includes/blocks/header.njk
- Правит вложенные label
- Заменяет div внутри button на span
=> Правки для html-валидации

.eleventy.js
Вдогонку к улучшению сортировки в #359
=> Учитывает при сортировке только буквы

.eleventy.js, src/styles/blocks/code-block.css, src/transforms/code-transform.js
=> Рефакторит блоки с кодом

src/views/article-index.11tydata.js, src/views/article-index.njk
Fix: Вывести в индексе категорию со статьями без категорий #346
=> Добавляет группу статей "Остальные"

src/styles/blocks/article.css, src/styles/blocks/code-block.css, src/styles/blocks/content.css, src/styles/blocks/doc.css, src/styles/blocks/header.css, src/views/doc.njk
Правит макет, чтобы основной контент был ближе к центру экрана
=> Правки макета статьи

src/includes/articles-gallery.njk, src/includes/blocks/logo.njk, src/styles/blocks/logo.css, src/styles/blocks/not-found.css, src/styles/index.css, src/views/404.njk, src/views/index.11tydata.js, src/views/index.njk, src/views/views.11tydata.js
- сделан рефактор стилей логотипа
- вывод featured-статей вынес в общий блок `eleventyComputed`
=> Добавляет вёрстку страницы 404

src/scripts/modules/search.js
=> Правит цвета для заголовков секций на странице поиска

src/scripts/modules/search.js, src/styles/blocks/search-hit.css
=> Выводит блоки кода в блоках описания текста

src/includes/blocks/featured-article.njk, src/views/views.11tydata.js
=> Удаляет символ ` в атрибуте title ссылок featured-статей

src/scripts/modules/header.js
=> Снимает фокус и чистит поле при закрытии header

src/includes/blocks/search.njk, src/styles/blocks/search.css, src/styles/blocks/suggestion-list.css
В списке подсказок поисковой формы идет обрезка контента, что неудобно. Предлагаю выводить все результаты сплошным списком.
=> Удаление переполнения в списке подсказок

src/layouts/base.njk
Исправляет баг, описанный в #437
=> Исправляет ошибку с глобальной переменной

src/includes/analytics/google.njk, src/includes/analytics/metrika.njk, src/layouts/base.njk
=> Добавляет тэг Google Analytics

src/includes/blocks/search.njk, src/scripts/modules/search.js, src/styles/blocks/font-theme.css, src/styles/blocks/header.css, src/styles/blocks/search.css, src/styles/blocks/suggestion-list.css
=> Правит отображение подсказок поиска

src/styles/blocks/index-section.css
- правка `scroll-margin` для Chrome. Прокрутка не доезжает
- добавление отступов для анимции `:target`. Fix: #409
=> Правки блоков групп статей

src/styles/blocks/articles-group.css, src/styles/blocks/callout.css, src/styles/blocks/content.css, src/styles/blocks/index-block.css, src/styles/blocks/index-section.css
=> Правки вёрстки на малых экранах

src/styles/blocks/article-indexes-list.css, src/styles/blocks/button.css, src/styles/blocks/header.css, src/styles/blocks/menu-toggle.css, src/styles/blocks/search-hit.css, src/styles/blocks/suggestion-list.css, src/styles/blocks/switch.css, src/styles/blocks/tag-filter.css
- добавляет эффекты наведения некоторым компонентам
- правит цвета для подложки шапки
=> Состояния наведения

src/includes/meta.njk, src/views/404.11tydata.js, src/views/all.11tydata.js, src/views/index.njk, src/views/page.11tydata.js, src/views/views.11tydata.js
- Правит h1 на главной странице. Fix: #465
- Удаляет лишние вычисления title
- Правит вывод title в теге head
=> Правки title и заголовков

src/styles/blocks/header.css
=> Визуально прячет меню, находящееся за пределами области просмотра.

src/styles/blocks/index-block.css, src/views/article-index.njk
=> Меняет позиционирование фильтров на страницах индексов

package.json
=> Добавляет фильтр для валидатора

.eleventy.js, src/transforms/iframe-attr-transform.js
=> Добавляет атрибуты к iframe

src/styles/blocks/search.css
=> Делает недоступными для мыши индикаторы горячих клавиш поиска

src/styles/blocks/article.css
=> Правит дёргание кнопки github для Blink

src/styles/blocks/header.css
=> Упрощает CSS-селекторы для шапки

src/scripts/modules/toc.js, src/transforms/toc-transform.js
Fix: https://github.com/doka-guide/content/issues/2262
=> Исключает заголовки внутри details из оглавления

src/styles/blocks/theme-toggle.css
=> Увеличивает контрастность переключателя темы

.eleventy.js, make-links.js
Добавляет пару правок (см. коммиты) для корректной работы сборки под Windows.
=> Правки сборки для Windows

src/styles/blocks/content.css, src/styles/blocks/details.css
Fix #711
Лучше всего смотреть в статье про `<html>` [в блоке про языки](https://doka-guide-platform-pr-712.surge.sh/html/html/#podskazki).
=> Добавляет ширину блоку details

.eleventy.js, src/includes/blocks/featured-article.njk, src/includes/blocks/header.njk, src/includes/blocks/social-card.njk, src/styles/blocks/article.css, src/transforms/code-transform.js, src/views/all.njk, src/views/article-index.njk, src/views/doc.11tydata.js, src/views/doc.njk, src/views/index.njk
=> Обработка бектиков для поля description

src/styles/blocks/header.css
=> Делает тень под шапкой более гладкой (#706)

src/styles/blocks/suggestion-list.css
=> Правит подсветку ссылок в поиске в шапке

src/transforms/callout-transform.js
=> Использует регулярку вместо итератора для получения символа эмоджи в callout

src/scripts/modules/search.js
=> Меняет порядок подсветки результата и замены бэктиков на code

src/styles/blocks/switch.css
=> Скругляет обводку переключателя сортировки

src/layouts/base.njk, src/scripts/modules/articles-index.js, src/styles/blocks/index-section.css, src/views/article-index.njk
- Удаляет autocomplete у radio-инпутов
- Добавляет сохранение состояния фильтра в url
=> Сохранение фильтра в url на странице индексов статей

src/includes/blocks/search.njk, src/scripts/modules/quick-search.js, src/styles/blocks/search.css, src/styles/blocks/suggestion-list.css
Нужно понять, в какой момент активировать/деактивировать управление клавишами и как работать с фокусом
=> Добавляет поддержку клавиатуры в быстром поиске

src/styles/blocks/article-nav.css
=> Предотвращает прокрутку страницы при скролле содержимого статьи

gulpfile.js, package-lock.json, package.json
- Удаляет пакет _gulp-tap_
- Добавляет обработку через transform-стрим
=> Меняет способ генерации social-изображений на стрим

src/includes/blocks/footer.njk
Чтобы на той стороне лучше понимали, что пришли от нас.
=> Добавляет метки к ссылке на Практикум

src/includes/blocks/search.njk, src/scripts/modules/quick-search.js, src/styles/blocks/search.css
- Удаляет индикатор Esc
- Меняет отступы и расположение элементов
=> Правит дизайн быстрого поиска в шапке

src/styles/blocks/article-image.css
=> Добавляет отступ между картинкой и подписью

src/views/doc.11tydata.js
=> Правит вычисление `docPath`

src/scripts/libs/throttle.js, src/scripts/modules/header.js, src/styles/blocks/header.css
Изменения:
- Фиксирование шапки при сколле наверх (Fix: #718).
- Уменьшено количество reflow-вычислений в моменты фиксирования.
Часть изменений была сделана ещё в прошлых PR, но здесь просто предлагаю закрыть issue (Fix: #630).
- Подправлены анимации шапки, чтобы "тень" скрывалась плавнее (Fix: #405).
=> Правит моменты появления/исчезновения шапки при скролле

src/views/404.njk
=> Добавляет стандартный хедер с поиском для 404 страницы

src/includes/blocks/header.njk, src/styles/blocks/header.css, src/views/article-index.njk, src/views/page.11tydata.js, src/views/page.njk
См. коммиты
Fix: #402
Fix: #609
Fix: #799
=> Правки отображения названий и категорий в "хлебных крошках"

src/styles/blocks/header.css
Баг закрался в [этом PR](https://github.com/doka-guide/platform/pull/804)
=> Добавляет показ категории в шапке на индексной странице на малых экранах

src/scripts/modules/article-aside.js, src/scripts/modules/header.js
FIx: #808
- Для каждого типа страниц добавляет условие скрытия шапки, даже если скроллить наверх
- Для быстрого скролла добавляется проверка, если шапка на самом верху, то убрать состояние фиксирования без анимаций
=> Добавляет дополнительные условия показа/скрытия шапки

CODEOWNERS
Мы раньше договорились на созвоне, что у @pepelsbey будут ключи от машины и мы сможем хотфиксить технические штуки не дожидаясь редактора. 
@tachisis в курсе и говорила, что это ок.
=> Добавляет @pepelsbey к овнерам документации

README.md
Fix #821
- Правит имя экшена platform-deploy — product-deploy
- Сортирует бейджи от линтинга к деплою
=> Фиксит старый бейдж, добавляет новый

src/includes/blocks/featured-article.njk, src/includes/blocks/footer.njk, src/views/views.11tydata.js
Продолжение этого [PR](https://github.com/doka-guide/content/pull/2606)
=> Исправление 301 ссылок на 200 

src/styles/blocks/article-nav.css
=> Удаляет подсветку при tap для кнопки содержания

src/transforms/details-transform.js, src/transforms/image-place-transform.js
Нам бы как-нибудь уже приделать это в виде экшенов в пул-реквесты.
А то конфиги есть, но ошибки тоже.
=> Фиксит по EditorConfig

src/styles/blocks/article-nav.css
=> Перемещает кнопку содержания для предотвращения наложения на элемент управления темой

src/styles/blocks/snow.css
Быстрый фикс для больших экранов
=> Раскидывает снежок на всю ширину

src/includes/blocks/snow-toggle.njk, src/layouts/base.njk, src/scripts/modules/snow-toggle.js, src/styles/blocks/snow.css
- Перенесла блок со снегом в конец страницы, чтобы не блокировать загрузку страницы этим несущественным элементом.
- Попыталась реализовать сохранение состояния в `localStorage`. Тут нужен опытный взгляд и совет.
@pepelsbey @monochromer буду благодарна за ваше ревью! 🙌
=> Фиксит снег

src/includes/blocks/header.njk, src/views/404.njk, src/views/all.njk, src/views/article-index.njk, src/views/doc.njk, src/views/index.njk, src/views/page.njk, src/views/search.njk
Это даёт возможность использовать глобальные eleventy-данные внутри импортируемых макросов
=> Пробрасывает родительский контекст с данными в компонент `header`

src/views/views.11tydata.js
- Использует новое поле `active`
- Меняет максимальное число статей для показа
=> Правит отображение featured-статей

src/scripts/core/search-commons.js, src/scripts/modules/search.js
Reverts doka-guide/platform#803
=> Revert "Использует возможности Algolia для подсветки результатов"

src/styles/blocks/figure.css, src/transforms/code-transform.js, src/transforms/image-place-transform.js
=> Добавляет парсинг произвольного HTML в подписях изображений

src/scripts/modules/search.js, src/styles/blocks/article-heading.css, src/styles/blocks/code-fix.css, src/styles/index.css, src/transforms/code-transform.js
Fix: #838
https://user-images.githubusercontent.com/105274/148846925-18fd9cc5-6a4c-4c85-979b-a2b2521f3506.mov
=> Правит высоту строк для текстовых блоков

src/includes/blocks/footer.njk
Сливать с тикетом из контента [#2750](https://github.com/doka-guide/content/pull/2750)
=> Правит название Практикума под новые правила

src/includes/blocks/header.njk, src/includes/blocks/logo.njk, src/views/404.njk, src/views/views.11tydata.js
- для старницы "Лицензии" добавлено `U©ᴥ©U`
- для страницы 404 значок логотип убран
=> Добавляет возможность менять логотип в зависимости от страницы

.eleventy.js, .env, .eslintignore, .gitignore, src/views/sitemap.11tydata.js, src/views/specials.11tydata.js, src/views/specials.njk
К событию ЯЛФ необходимо добавить описание на сайте. Связано с [этим](https://github.com/doka-guide/content/pull/2762) PR.
=> Добавляет страницы событий / оферов

src/includes/blocks/logo.njk, src/scripts/modules/header-quick-search-presenter.js, src/scripts/modules/logo.js, src/scripts/modules/search.js, src/styles/base-colors.css, src/styles/blocks/logo.css, src/styles/dark-theme.css, src/styles/light-theme.css
=> Добавляет анимацию логотипа при поиске

src/styles/blocks/featured-article.css
=> Добавляет эффект hover для карточки статьи

src/styles/blocks/callout.css
=> Добавляет перенос эмоджи в callout

CODEOWNERS
=> Обновляет CODEOWNER'ов

.github/workflows/product-deploy.yml
=> Делает ссылки правильными

src/styles/blocks/index-block.css
=> Прибивает футер к низу

.eleventy.js, src/views/views.11tydata.js
=> Исправляет проблему с аватарами участников

src/layouts/base.njk
Было решено контролировать загрузку метрик с помощью Nginx. Данный pull request удаляет метрики с самого сайта, чтобы не дублировать их.
=> Удаляет метрики

src/views/person.11tydata.js, src/views/person.njk
Поправил. Впервые замечено [тут](https://github.com/doka-guide/content/pull/3549#issuecomment-1207762754)
=> Исправляет никнеймы для twitter и behance

src/styles/blocks/text-control.css
=> Убирает скругление поля на iOS

src/styles/blocks/theme-toggle.css
=> Скругляет обводку переключателей цветовой темы

src/scripts/modules/last-update.js
Привет, Дока! 🐶
1. Заменил if-else на ассоциативный поиск, немного поменял нейминг.
2. У себя тестил в консольке, работает.
3. **Минус?:** порядок значений в `piecesToSeconds` важен - по убыванию (но так было и до рефакторинга). Подсвечиваю.
P. S. Одну и ту же калькуляцию вынес в отдельный метод.
Буду рад советам и критике, первый коммит в опен-сорс :)
_Извиняюсь, что одними и теми же коммитами в ишью нафлудил (--amend)._
=> Рефакторит вычисление последнего времени обновления #206

src/includes/articles-gallery.njk, src/includes/related-articles-gallery.njk, src/scripts/modules/articles-gallery.js, src/styles/blocks/featured-articles-list.css, src/styles/index.css, src/styles/index.sc.css
Кажется, пропущена буква `l` в `artices`, предлагаю исправить.
=> Правит нейминг классов

src/views/views.11tydata.js
=> Исправляет список статей с ответами участника

.github/workflows/pr-preview.yml, src/styles/blocks/header.css, src/styles/blocks/person-badges.css, src/styles/blocks/person-links-list.css, src/styles/blocks/person-page.css
На текущий момент, при изменении ширины окна менее 920px, элемент с ачивками и другой информацией (**person-badges__meta**) залазит на элемент (**person-badges__header**) - перекрывая его, и ещё появляется нижний скролл.
Скорректировал адаптив: при ширине окна менее 686px, элемент **person-badges__meta** перемещается под элемент **person-badges__header**, а нижний скролл - отсутствует.
Также, из-за изменений выше, понадобилось внести изменения в адаптив для хлебных крошек, чтобы кнопка многоточие (**menu-toggle**) не залазила на ссылку "**Участники**", когда та ещё не исчезла.
=> Скорректировал адаптивную вёрстку на странице профиля участника

.eslintrc.json, jest.config.js, jest.setup.js, package-lock.json, package.json, src/scripts/libs/__tests__/toc-text-crop-test.js, src/scripts/modules/toc-text-crop.js
Пересоздал пиар.
Что внутри:
1. Функция `clipContent` выполняет задачу и выглядит проще, а также не зависит от длины строк-входных данных;
2. Тест тестирует функцию `clipContent` на главный критерий: длина предложений после обработки должна быть 90 символов и меньше. Проверяется с помощью четырех предложений длиной более 90 символов, ровно 90, меньше 90 и предложением с пробелами по сторонам;
3. Добавил `jsdom` и `jest-environment-jsdom` для эмуляции DOM. Две глобальные переменные `TextEncoder` и `TextDecoder` в файле `jest.setup.js` нужны для корректной работы `jsdom`.
=> Рефакторит функцию `toc-text-crop.js` и добавляет тест

src/views/people.njk
Добавила скрытый заголовок первого уровня для страницы участников.
Closes #1053.
=> Добавляет `<h1>` на страницу всех участников

src/libs/github-contribution-service/github-contribution-service.js
Решил я проблему, кажется. Больше сборка не должна падать.
=> Решает проблему сборки с падение по таймауту

src/scripts/modules/filter-panel.js, src/scripts/modules/search-page-filter.js
Из-за ошибки в этих скриптах как раз ломаются те, что подключаются вслед за ними. Например, кнопка в практике и собесах.
=> Чинит скрипт для открытия меню с фильтрами (участники, поиск)

src/styles/landing.css, src/views/index.njk
Добавляет заголовок главы про акклиматизацию.
=> Добавляет заголовок новой главы

src/includes/questions.njk, src/styles/blocks/questions.css
Послушала @igsekor и сделала одну кнопку "Задать вопрос" прямо под заголовком.
Помогите, пожалуйста, со ссылками на гитхаб 😅
Ссылка "Задать вопрос" в идеале должна вести на шаблон создания ишью. Там можно дать все необходимые пояснения закомменченным кодом. Я пока не умею создавать шаблоны :D
Ссылка "Я знаю ответ" может вести в папку с файлами, по аналогии с "Редактировать на гитхаб" в боковой колонке. Или лучше сделать микродок, где объяснить, как добавить ответ на собеседование?
=> Добавляет кнопки в раздел "Собеседование"

src/scripts/libs/__tests__/last-update-test.js, src/scripts/modules/last-update.js
Написал тест для вывода времени обновления статей. Проверяет, как получается время в секундах, минутах, часах, а также что округляет в большую сторону, а ещё что не работает, если прошли сутки.
=> Добавляет тест модуля `last-update`

src/styles/blocks/callout.css
Добавляет отступы между параграфами во врезках, если уж они, параграфы количеством больше одного, там бывают.
=> Добавляет отступы для параграфов во врезках

src/styles/blocks/switch.css
Потерялась единица измерения для перехода
=> Исправляет опечатку

src/images/letter.svg, src/views/index.njk
=> Добавляет ссылку на пятую главу

src/includes/blocks/footer.njk
=> Исправляет ссылки в футере

src/includes/blocks/social-card.njk, src/styles/blocks/social-card.css, src/views/sc-all.11tydata.js, src/views/sc-all.njk, src/views/sc-index.njk, src/views/sc.njk
=> Добавляет OG-картинку для раздела

src/views/article-index-json.11tydata.js, src/views/article-index-json.njk
Этот пиар завершает серию пиаров для обеспечения работы API
=> Добавляет выгрузку сокращённых док всего раздела

src/views/index.njk
=> Убирает баннер стрима с главной

src/includes/blocks/logo.njk, src/scripts/modules/logo.js, src/scripts/modules/theme-toggle.js, src/styles/base-colors.css, src/styles/blocks/logo.css, src/styles/dark-theme.css, src/styles/light-theme.css
Заменила цвета всех разделов на оранжевые.
В светлой теме ярко-оранжевый, в тёмной — поспокойнее.
@skorobaeus @TatianaFokina зацените, как вам =)
@igsekor @HellSquirrel часть задумки — по умолчанию включать тёмную тему для всех пользователей. Пожалуйста, помогите с этим 🙏
=> Не мёрджить до 31 октября! 👻 Шалость =)

package-lock.json
=> Обновляет модуль со списком браузеров

src/styles/blocks/feedback-form.css
Исправляет центрирование заголовка фидбэк-формы.
Closes #1225
=> Поправляет выравнивание заголовка фидбэк-формы

src/promos/oklich-stream.md
=> Добавляет промо

.eleventy.js, src/views/doc.11tydata.js
В этом пиаре поправил не только скрипты и конфигурацию для подготовки материалы для рубрик «На практике» и «На собеседовании», но и поработал с настройкой штатного веб-сервера, который появился во второй версии. Теперь всё работает!
=> Хот-фикс для новой версии (практики и интервью)

src/promos/border-job.md
=> Добавляет промо про стрим трудоустройства за границей

.github/workflows/w3c-validator.yml, src/views/views.11tydata.js
Вот и до этого экшена добрались :)
=> Чинит валидацию W3С

src/styles/blocks/featured-article.css, src/styles/blocks/link.css
Сделала всю фичеринг-карточку кликабельной. Конечно, не обошлось без борьбы со специфичностью из-за стилей для оффлайн Доки 🥲
=> Расширяет область клика у карточки

src/promos/pwa-stream.md
Поменял "сегодня" на что-то более актуальное
=> Обновляет промо для PWA

src/views/index.njk
Меняет старые ссылки на новые — связан с [этим пиаром](https://github.com/doka-guide/content/pull/5365) в контенте.
=> Меняет ссылки

.eleventy.js
=> Исправляет ошибку в RSS-фиде

src/images/icons/icon.svg
Добавила внутрь svg-фавиконки стили для смены цвета в зависимости от выбранной темы ОС у пользователя.
=> Меняет цвет svg-файвиконки под тему в ОС

src/includes/questions.njk
Меняет текст и ссылку:
Это вопрос без ответа. Вы можете помочь! Почитайте о том, как [контрибьютить в Доку](https://github.com/doka-guide/content/blob/main/docs/interviews.md).
Это вопрос без ответа. Вы можете помочь! Чтобы написать ответ, следуйте [инструкции](https://github.com/doka-guide/content/blob/main/docs/interviews.md#%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D0%BE%D1%82%D0%B2%D0%B5%D1%82).
Фикс для: #1289
=> Исправляет блок с информацией об отсутствии ответов на вопрос

src/includes/blocks/footer.njk, src/includes/meta.njk
Превью: https://platform-1307.dev.doka.guide/
(количество звёздочек на превью отличается от реальности)
=> Добавляет кнопку со звёздочками GH в футер

src/styles/blocks/person-page.css
Поломалась левая колонка на странице участника, если мало статей. Починила.
=> Чинит страницу участника

src/includes/blocks/snow-25.njk
Превью: https://platform-1319.dev.doka.guide/
=> Добавляет `role=presentation` для канваса со снегом

package-lock.json, package.json
У нас сейчас используется версия 1.0.0
Текущая версия: 2.22.0
=> Поднимает версию web-features до 2.22.0

.dockerignore, .gitignore
Предлагаю добавить файлы настроек проектов VSCode и Sublime Text в исключения, по аналогии с репозиторием контента.
Эти файлы хрянят локальные настройки и не должны попадать в репозиторий.
Добавляю маски:
*.code-workspace
*.sublime-workspace
*.sublime-project
в список исключений `.gitignore`
=> Добавляет файлы VSCode и Sublime Text в список исключений .gitignore
